version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest
    versions:
    - ">= 0"
  - dependency-name: setuptools
    versions:
    - ">= 0"
  - dependency-name: twine
    versions:
    - ">= 0"
  - dependency-name: wheel
    versions:
    - ">= 0"
  - dependency-name: dragonfly-energy
    versions:
    - 1.12.0
    - 1.12.1
    - 1.12.10
    - 1.12.11
    - 1.12.12
    - 1.12.14
    - 1.12.15
    - 1.12.16
    - 1.12.18
    - 1.12.19
    - 1.12.20
    - 1.12.22
    - 1.12.23
    - 1.12.24
    - 1.12.25
    - 1.12.27
    - 1.12.28
    - 1.12.29
    - 1.12.3
    - 1.12.30
    - 1.12.33
    - 1.12.34
    - 1.12.36
    - 1.12.37
    - 1.12.38
    - 1.12.40
    - 1.12.42
    - 1.12.43
    - 1.12.44
    - 1.12.45
    - 1.12.46
    - 1.12.47
    - 1.12.5
    - 1.12.6
    - 1.12.64
    - 1.12.7
    - 1.12.8
    - 1.12.9
  - dependency-name: pollination-dsl
    versions:
    - 0.10.0
    - 0.10.1
    - 0.10.2
    - 0.10.3
    - 0.11.0
    - 0.11.2
    - 0.11.3
    - 0.11.4
    - 0.9.6
    - 0.9.7
